env:
  - RSPEC_PATTERN="spec/{controllers,features,helpers,lib,mailers,models,usermanual}/**/*.rb"  CI_NODE=1
  - RSPEC_PATTERN="spec/integration/{running_tests,comet,feedback,requests}/**/*.rb" CI_NODE=2
  - RSPEC_PATTERN="spec/integration/*.rb" CI_NODE=3
  - CI_NODE=4
  - CI_NODE=5


language: ruby
rvm:
  - 2.2.0

git:
  submodules: false

script:
  - env
